### ISSUE TITLE
Overall review and issues with the styles.

### ISSUE THREAD

**Issue by Efreak** [tr4656/SGUserstyle#3]
I do use steamgifts plus, and most of those pages look fine. However, the white text that shows up just about everywhere is far too bright for the dark background, so tone it down a bit. Some of the red and blue links are still a tiny bit too dark as well, and the green checkmarks everywhere should be brightened a bit or have darked backgrounds--you can't tell that they're green. Colors in the edit box could use changing, as could the menu background colors, perhaps. To be plain, the following pages look terrible:
- [created](http://www.steamgifts.com/manage/created)
- [entries](http://www.steamgifts.com/manage/entries)
- [won](http://www.steamgifts.com/manage/won)
- [wishlist](http://www.steamgifts.com/wishlist) (particularly if you hover over an item)

Overall, this looks nice, and I like it _much_ better than the default theme, as it fits in very well with my current OS theming whether I'm running linux or windows. A userscript would be preferred over stylish script, as chrome supports those natively. ~~I'll crosspost this comment on github.~~ I also posted this in the forums.

Edit: the blue bar at the bottom should probably be changed somewhat, as it looks a bit strange. So should the backgrounds on the advertisements at the bottom of the screen. Much of the text also appears too small to me, at least on a dark theme. (Yes, I realize it's the same size and it looks fine on the bright theme)

**Comment by Efreak** [comment]
The colors on the user page are probably completely done, but there's a couple bugs left there:
- you've left a space for the gifter's avatar, but the avatar is only shown at the top of the userpage, not on the giveaways. 
- deleted giveaways show the contrib amount on a second line, under the 'private' or 'group' tag. (these could also probably be a slightly darker color).

**Comment by tr4656** [comment]
Created/Entries/Won are all done. Userscript via userstyles seem to work.

**Comment by Ryahn** [comment]
Seems to be all fixed now
